### ISSUE TITLE
Add key unit tests

### ISSUE THREAD

**Issue by thehale** [thehale/power-farming#1]
```[tasklist]
# Tasks
- [ ] Ensure cocoa beans face the same way after auto-replanting (`createBlockData` doesn't guarantee that)
- [ ] Doesn't retrigger when elapsed time is smaller than some interval
- [ ] If out of seeds, drop the stuff without replanting
- [ ] If crouching, drop the seeds without replanting
- [ ] If not a crop, propagate the event with no extra effects (treat as normal)
```

These items are already working in the plugin, I just want automated tests to ensure they continue working as expected.
